services:
  - type: web
    name: corretor-de-arquivos-api
    env: docker
    rootDir: unimed-tools-backend
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 10000
      - key: SGU_API_KEY
        sync: false
      - key: SGU_API_BASE_URL
        value: https://api.lorena.sgusuite.com.br
      - key: SGU_API_PROCEDURE_PATH
        value: /api/procedure/p_prcssa_dados
      - key: SGU_API_EXECUTION_PATH
        value: /api/procedure/p_prcssa_dados